name: Deploy to PRODUCTION

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          # Replace with your deployment commands
          echo "Deploying to prod environment from branch: ${{ github.event.workflow_run.head_branch }}"
