name: Deploy to QA

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "dev"

jobs:
  deploy:
    if: ${{github.event.workflow_run.head_branch != 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Deploy to QA environment
        run: |
          # Replace with your deployment commands
          echo "Deploying to QA environment from branch: ${{ github.event.inputs.branch }}"
